version: '3.9'

services:
  db:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - migrate
  
  migrate:
    image: migrate/migrate
    volumes:
      - ./schema:/migrations
    env_file:
      - .env
    command: ["-path", "/migrations", "-database",  "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSLMODE", "up"]
    depends_on:
      - db

volumes:
 data: